{% set name = "is-number" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jacobtomlinson/{{ name }}/archive/{{ version }}.tar.gz
  sha256: c98ffda630d3b2bcf958b8842376520483a69f938e889bb60778fd65cc6e6617

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - is_number

about:
  home: https://github.com/jacobtomlinson/is-number
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python library to determine if something is a number.
  description: |
    A Python library to determine if something is a number.
  doc_url: https://github.com/jacobtomlinson/is-number
  dev_url: https://github.com/jacobtomlinson/is-number

extra:
  recipe-maintainers:
    - jacobtomlinson
